/**
 * Eventerz Anchor program - instruction builders and account decoding.
 *
 * Hand-rolled rather than generated by `@coral-xyz/anchor`, for three reasons
 * that all point the same way:
 *
 *   1. Anchor's client pulls a large dependency tree into a Next.js bundle to
 *      do what amounts to eight byte-array concatenations.
 *   2. The mobile app has to build the identical instructions, and Anchor's
 *      client is awkward under React Native (Node polyfills, `Buffer`,
 *      dynamic `require`). One implementation that ports 1:1 beats two that
 *      drift.
 *   3. Everything here is fixed at compile time - discriminators, layouts,
 *      account ordering - so there is nothing an IDL loader would resolve at
 *      runtime that is not already known.
 *
 * The cost is that this file and `programs/eventerz/src/lib.rs` have to agree
 * by hand. `npm run idl:sync` in the program workspace recomputes every
 * discriminator from the built IDL and exits non-zero if this file disagrees, so
 * a rename in Rust that is not mirrored here fails a build rather than failing in
 * a user's wallet.
 *
 * @see ../../../../Eventerz Program/programs/eventerz/src/lib.rs
 */

import {
  PublicKey,
  SystemProgram,
  TransactionInstruction,
} from '@solana/web3.js';
/*
 * Explicit import, unlike the website's copy of this file, which gets `Buffer`
 * as a global from `@types/node`. Hermes has no `Buffer` and this project has no
 * Node types on purpose, so relying on the global would typecheck nowhere and
 * crash at runtime in a release build. `src/polyfills.ts` installs the same
 * implementation globally for web3.js's own internals.
 */
import { Buffer } from 'buffer';

import { integrationsConfig } from '@/constants/config';

/* -------------------------------------------------------------------------- */
/*  Program identity                                                           */
/* -------------------------------------------------------------------------- */

/**
 * The deployed program, or null when there is none.
 *
 * Null is the normal state until the program is deployed, and every caller has
 * to handle it. Returning a fabricated address instead would let the UI offer
 * on-chain actions that cannot work - which is the failure mode the mobile
 * adapter already refuses to produce.
 */
export function eventerzProgramId(): PublicKey | null {
  const raw = process.env.EXPO_PUBLIC_EVENTERZ_PROGRAM_ID?.trim();
  if (!raw) return null;
  try {
    return new PublicKey(raw);
  } catch {
    // A malformed id is a deployment mistake, not a user error. Log it once
    // and behave as if unset rather than throwing inside a render.
    if (typeof console !== 'undefined') {
      console.warn('[eventerz] EXPO_PUBLIC_EVENTERZ_PROGRAM_ID is not a valid address');
    }
    return null;
  }
}

export const isProgramDeployed = (): boolean => eventerzProgramId() !== null;

const EVENT_SEED = new TextEncoder().encode('event');
const SEAT_SEED = new TextEncoder().encode('seat');

/* -------------------------------------------------------------------------- */
/*  Discriminators                                                             */
/* -------------------------------------------------------------------------- */

/**
 * Anchor prefixes every instruction with the first eight bytes of
 * `sha256("global:<snake_case_name>")`, and every account with
 * `sha256("account:<StructName>")`.
 *
 * Hard-coded because they are constants of the program's source text, and
 * because hashing at runtime would mean a SHA-256 implementation in the mobile
 * bundle for a value that never changes. The test suite recomputes them.
 */
const IX = {
  createEvent: [49, 219, 29, 203, 22, 98, 100, 87],
  updateEvent: [70, 108, 211, 125, 171, 176, 25, 217],
  cancelEvent: [55, 143, 36, 45, 59, 241, 89, 119],
  claimSeat: [47, 217, 3, 139, 51, 238, 55, 107],
  approveSeat: [54, 208, 161, 60, 191, 220, 112, 139],
  declineSeat: [114, 22, 65, 96, 183, 142, 191, 248],
  releaseSeat: [222, 199, 126, 134, 66, 153, 185, 190],
  checkIn: [209, 253, 4, 217, 250, 241, 207, 50],
} as const;

const ACCOUNT_DISCRIMINATOR = {
  event: [98, 136, 32, 165, 133, 231, 243, 154],
  seat: [251, 85, 162, 147, 128, 212, 122, 178],
} as const;

/* -------------------------------------------------------------------------- */
/*  Borsh encoding - only the shapes this program uses                         */
/* -------------------------------------------------------------------------- */

class Writer {
  private bytes: number[] = [];

  u8(value: number): this {
    this.bytes.push(value & 0xff);
    return this;
  }

  bool(value: boolean): this {
    return this.u8(value ? 1 : 0);
  }

  raw(values: ArrayLike<number>): this {
    for (let i = 0; i < values.length; i++) this.bytes.push(values[i] & 0xff);
    return this;
  }

  u32(value: number): this {
    for (let i = 0; i < 4; i++) this.bytes.push((value >>> (i * 8)) & 0xff);
    return this;
  }

  /**
   * 64-bit little-endian, via `BigInt`.
   *
   * Numbers cannot be used here: lamport amounts and Unix timestamps in
   * milliseconds both exceed `Number.MAX_SAFE_INTEGER` in plausible cases, and
   * a silently truncated amount is the worst possible bug in a payment path.
   * `BigInt.asUintN` handles negative timestamps (i64) with the same code by
   * reinterpreting the two's-complement bits.
   */
  i64(value: bigint): this {
    let v = BigInt.asUintN(64, value);
    for (let i = 0; i < 8; i++) {
      this.bytes.push(Number(v & 0xffn));
      v >>= 8n;
    }
    return this;
  }

  /** Borsh `Option<T>`: a presence byte, then the value when present. */
  option<T>(value: T | null | undefined, write: (w: Writer, v: T) => void): this {
    if (value === null || value === undefined) return this.u8(0);
    this.u8(1);
    write(this, value);
    return this;
  }

  toBuffer(): Buffer {
    return Buffer.from(this.bytes);
  }
}

class Reader {
  private offset = 0;
  constructor(private readonly data: Uint8Array) {}

  skip(n: number): this {
    this.offset += n;
    return this;
  }

  u8(): number {
    return this.data[this.offset++];
  }

  bool(): boolean {
    return this.u8() === 1;
  }

  bytes(n: number): Uint8Array {
    const slice = this.data.slice(this.offset, this.offset + n);
    this.offset += n;
    return slice;
  }

  u32(): number {
    let value = 0;
    for (let i = 0; i < 4; i++) value += this.data[this.offset++] * 2 ** (i * 8);
    return value;
  }

  u64(): bigint {
    let value = 0n;
    for (let i = 0; i < 8; i++) {
      value += BigInt(this.data[this.offset++]) << BigInt(i * 8);
    }
    return value;
  }

  i64(): bigint {
    return BigInt.asIntN(64, this.u64());
  }

  pubkey(): PublicKey {
    return new PublicKey(this.bytes(32));
  }
}

/* -------------------------------------------------------------------------- */
/*  Addresses                                                                  */
/* -------------------------------------------------------------------------- */

/**
 * A Postgres UUID as the 16 raw bytes the program seeds accounts with.
 *
 * Strict about the format: a UUID that has been truncated or had its dashes
 * mangled would still produce *some* seed and therefore some address, and a
 * seat written to the wrong event account is not recoverable.
 */
export function uuidToBytes(uuid: string): Uint8Array {
  const hex = uuid.replace(/-/g, '').toLowerCase();
  if (!/^[0-9a-f]{32}$/.test(hex)) {
    throw new Error(`Not a UUID: ${uuid}`);
  }
  const bytes = new Uint8Array(16);
  for (let i = 0; i < 16; i++) {
    bytes[i] = Number.parseInt(hex.slice(i * 2, i * 2 + 2), 16);
  }
  return bytes;
}

/** The event account's address, derivable offline from a row id alone. */
export function eventPda(eventId: string, programId: PublicKey): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(EVENT_SEED), Buffer.from(uuidToBytes(eventId))],
    programId,
  )[0];
}

/** One seat per (event, attendee), enforced by the address itself. */
export function seatPda(
  eventAccount: PublicKey,
  attendee: PublicKey,
  programId: PublicKey,
): PublicKey {
  return PublicKey.findProgramAddressSync(
    [Buffer.from(SEAT_SEED), eventAccount.toBuffer(), attendee.toBuffer()],
    programId,
  )[0];
}

/* -------------------------------------------------------------------------- */
/*  Instructions                                                               */
/* -------------------------------------------------------------------------- */

export interface CreateEventArgs {
  eventId: string;
  host: PublicKey;
  capacity: number;
  startsAt: Date | string;
  /** Omit for an event with no stated end - encoded as 0, as the program expects. */
  endsAt?: Date | string | null;
  priceLamports?: bigint | number;
  requiresApproval?: boolean;
}

/** Seconds since the epoch, which is what a Solana `i64` timestamp is. */
function unixSeconds(value: Date | string | null | undefined): bigint {
  if (value === null || value === undefined) return 0n;
  const ms = value instanceof Date ? value.getTime() : Date.parse(value);
  if (Number.isNaN(ms)) throw new Error(`Not a date: ${String(value)}`);
  return BigInt(Math.floor(ms / 1000));
}

export function createEventInstruction(
  args: CreateEventArgs,
  programId: PublicKey,
): TransactionInstruction {
  const event = eventPda(args.eventId, programId);

  const data = new Writer()
    .raw(IX.createEvent)
    .raw(uuidToBytes(args.eventId))
    .u32(args.capacity)
    .i64(unixSeconds(args.startsAt))
    .i64(unixSeconds(args.endsAt))
    .i64(BigInt(args.priceLamports ?? 0))
    .bool(args.requiresApproval ?? false)
    .toBuffer();

  return new TransactionInstruction({
    programId,
    keys: [
      { pubkey: event, isSigner: false, isWritable: true },
      { pubkey: args.host, isSigner: true, isWritable: true },
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
    ],
    data,
  });
}

export interface UpdateEventArgs {
  eventId: string;
  host: PublicKey;
  capacity?: number | null;
  startsAt?: Date | string | null;
  endsAt?: Date | string | null;
  priceLamports?: bigint | number | null;
  requiresApproval?: boolean | null;
}

export function updateEventInstruction(
  args: UpdateEventArgs,
  programId: PublicKey,
): TransactionInstruction {
  const data = new Writer()
    .raw(IX.updateEvent)
    .option(args.capacity ?? null, (w, v) => w.u32(v))
    .option(args.startsAt ?? null, (w, v) => w.i64(unixSeconds(v)))
    .option(args.endsAt ?? null, (w, v) => w.i64(unixSeconds(v)))
    .option(args.priceLamports ?? null, (w, v) => w.i64(BigInt(v)))
    .option(args.requiresApproval ?? null, (w, v) => w.bool(v))
    .toBuffer();

  return hostInstruction(args.eventId, args.host, programId, data);
}

export function cancelEventInstruction(
  eventId: string,
  host: PublicKey,
  programId: PublicKey,
): TransactionInstruction {
  return hostInstruction(
    eventId,
    host,
    programId,
    new Writer().raw(IX.cancelEvent).toBuffer(),
  );
}

/** `UpdateEvent` context: the event, then the host as signer. */
function hostInstruction(
  eventId: string,
  host: PublicKey,
  programId: PublicKey,
  data: Buffer,
): TransactionInstruction {
  return new TransactionInstruction({
    programId,
    keys: [
      { pubkey: eventPda(eventId, programId), isSigner: false, isWritable: true },
      { pubkey: host, isSigner: true, isWritable: false },
    ],
    data,
  });
}

export function claimSeatInstruction(
  eventId: string,
  attendee: PublicKey,
  host: PublicKey,
  programId: PublicKey,
): TransactionInstruction {
  const event = eventPda(eventId, programId);
  return new TransactionInstruction({
    programId,
    keys: [
      { pubkey: event, isSigner: false, isWritable: true },
      { pubkey: seatPda(event, attendee, programId), isSigner: false, isWritable: true },
      { pubkey: attendee, isSigner: true, isWritable: true },
      // Writable because a paid event transfers the price to it in the same
      // instruction.
      { pubkey: host, isSigner: false, isWritable: true },
      { pubkey: SystemProgram.programId, isSigner: false, isWritable: false },
    ],
    data: new Writer().raw(IX.claimSeat).toBuffer(),
  });
}

/** `HostSeatAction`: approve, decline and check-in share one account layout. */
function hostSeatInstruction(
  discriminator: readonly number[],
  eventId: string,
  attendee: PublicKey,
  host: PublicKey,
  programId: PublicKey,
): TransactionInstruction {
  const event = eventPda(eventId, programId);
  return new TransactionInstruction({
    programId,
    keys: [
      { pubkey: event, isSigner: false, isWritable: true },
      { pubkey: seatPda(event, attendee, programId), isSigner: false, isWritable: true },
      { pubkey: host, isSigner: true, isWritable: false },
    ],
    data: new Writer().raw(discriminator).toBuffer(),
  });
}

export const approveSeatInstruction = (
  eventId: string,
  attendee: PublicKey,
  host: PublicKey,
  programId: PublicKey,
) => hostSeatInstruction(IX.approveSeat, eventId, attendee, host, programId);

export const declineSeatInstruction = (
  eventId: string,
  attendee: PublicKey,
  host: PublicKey,
  programId: PublicKey,
) => hostSeatInstruction(IX.declineSeat, eventId, attendee, host, programId);

export const checkInInstruction = (
  eventId: string,
  attendee: PublicKey,
  host: PublicKey,
  programId: PublicKey,
) => hostSeatInstruction(IX.checkIn, eventId, attendee, host, programId);

export function releaseSeatInstruction(
  eventId: string,
  attendee: PublicKey,
  programId: PublicKey,
): TransactionInstruction {
  const event = eventPda(eventId, programId);
  return new TransactionInstruction({
    programId,
    keys: [
      { pubkey: event, isSigner: false, isWritable: true },
      { pubkey: seatPda(event, attendee, programId), isSigner: false, isWritable: true },
      { pubkey: attendee, isSigner: true, isWritable: true },
    ],
    data: new Writer().raw(IX.releaseSeat).toBuffer(),
  });
}

/* -------------------------------------------------------------------------- */
/*  Reading accounts                                                           */
/* -------------------------------------------------------------------------- */

export interface OnChainEvent {
  eventId: string;
  host: PublicKey;
  capacity: number;
  confirmed: number;
  checkedIn: number;
  startsAt: Date;
  endsAt: Date | null;
  priceLamports: bigint;
  requiresApproval: boolean;
  cancelled: boolean;
}

export type OnChainSeatStatus = 'requested' | 'confirmed' | 'declined';

export interface OnChainSeat {
  event: PublicKey;
  attendee: PublicKey;
  status: OnChainSeatStatus;
  claimedAt: Date;
  checkedInAt: Date | null;
}

function matches(data: Uint8Array, discriminator: readonly number[]): boolean {
  return discriminator.every((byte, i) => data[i] === byte);
}

function bytesToUuid(bytes: Uint8Array): string {
  const hex = Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
  return [
    hex.slice(0, 8),
    hex.slice(8, 12),
    hex.slice(12, 16),
    hex.slice(16, 20),
    hex.slice(20),
  ].join('-');
}

/**
 * Decode an event account, or null when the bytes are not one.
 *
 * Returning null rather than throwing on a discriminator mismatch is
 * deliberate: the caller usually asked for an address that may simply not
 * exist yet - an event created before the program was deployed - and that is
 * an expected answer, not an error.
 */
export function decodeEventAccount(data: Uint8Array): OnChainEvent | null {
  if (data.length < 8 || !matches(data, ACCOUNT_DISCRIMINATOR.event)) return null;

  const r = new Reader(data).skip(8);
  const eventId = bytesToUuid(r.bytes(16));
  const host = r.pubkey();
  const capacity = r.u32();
  const confirmed = r.u32();
  const checkedIn = r.u32();
  const startsAt = r.i64();
  const endsAt = r.i64();
  const priceLamports = r.u64();
  const requiresApproval = r.bool();
  const cancelled = r.bool();

  return {
    eventId,
    host,
    capacity,
    confirmed,
    checkedIn,
    startsAt: new Date(Number(startsAt) * 1000),
    // Zero is the program's "no stated end", not 1970.
    endsAt: endsAt === 0n ? null : new Date(Number(endsAt) * 1000),
    priceLamports,
    requiresApproval,
    cancelled,
  };
}

export function decodeSeatAccount(data: Uint8Array): OnChainSeat | null {
  if (data.length < 8 || !matches(data, ACCOUNT_DISCRIMINATOR.seat)) return null;

  const r = new Reader(data).skip(8);
  const event = r.pubkey();
  const attendee = r.pubkey();
  const statusByte = r.u8();
  const claimedAt = r.i64();
  const checkedInAt = r.i64();

  const status: OnChainSeatStatus =
    statusByte === 0 ? 'requested' : statusByte === 1 ? 'confirmed' : 'declined';

  return {
    event,
    attendee,
    status,
    claimedAt: new Date(Number(claimedAt) * 1000),
    checkedInAt: checkedInAt === 0n ? null : new Date(Number(checkedInAt) * 1000),
  };
}

/** Explorer link for a signature, on whichever cluster this build targets. */
export function explorerTxUrl(signature: string): string {
  const cluster = integrationsConfig.solanaNetwork;
  const suffix = cluster === 'mainnet-beta' ? '' : `?cluster=${cluster}`;
  return `https://explorer.solana.com/tx/${signature}${suffix}`;
}
